services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: job_test_thunderbite_app
    container_name: job_test_thunderbite_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - vendor:/var/www/html/vendor
    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret

  web:
    image: nginx:alpine
    container_name: job_test_thunderbite_web
    restart: unless-stopped
    ports:
      - "9000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: job_test_thunderbite_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
  vendor:
